export const ROUTES = {
  home: '/',
  search: '/recherche',
  offers: '/offres',
  offer: (slug: string) => `/offres/${slug}`,
  omra: '/omra',
  destinations: '/destinations',
  destination: (slug: string) => `/destinations/${slug}`,
  blog: '/blog',
  article: (slug: string) => `/blog/${slug}`,
  about: '/a-propos',
  contact: '/contact',
  faq: '/faq',
  cgv: '/cgv',
  privacy: '/confidentialite',
  legal: '/mentions-legales',

  // Auth
  login: '/connexion',
  register: '/inscription',
  forgotPassword: '/mot-de-passe-oublie',
  verifyEmail: '/verification-email',

  // Account
  account: '/compte',
  bookings: '/compte/reservations',
  booking: (id: string) => `/compte/reservations/${id}`,
  favorites: '/compte/favoris',
  travelers: '/compte/voyageurs',
  profile: '/compte/profil',
  notifications: '/compte/notifications',
  settings: '/compte/parametres',

  // Booking flow
  reservationOptions: (offerId: string) => `/reservation/${offerId}/options`,
  reservationTravelers: (offerId: string) => `/reservation/${offerId}/voyageurs`,
  reservationRecap: (offerId: string) => `/reservation/${offerId}/recap`,
  reservationPayment: (offerId: string) => `/reservation/${offerId}/paiement`,
  reservationConfirmation: (offerId: string) => `/reservation/${offerId}/confirmation`,
  reservationFailed: '/reservation/echec',

  // Admin
  admin: '/admin',
  adminBookings: '/admin/reservations',
  adminBooking: (id: string) => `/admin/reservations/${id}`,
  adminPayments: '/admin/paiements',
  adminOffers: '/admin/offres',
  adminNewOffer: '/admin/offres/nouvelle',
  adminEditOffer: (id: string) => `/admin/offres/${id}/edition`,
  adminClients: '/admin/clients',
  adminClient: (id: string) => `/admin/clients/${id}`,
  adminDestinations: '/admin/destinations',
  adminBlog: '/admin/blog',
  adminPromos: '/admin/promos',
  adminPages: '/admin/pages',
  adminUsers: '/admin/utilisateurs',
  adminSettings: '/admin/parametres',
  adminAudit: '/admin/audit',
} as const;
